name: Actions
on: [push]

jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Configure python
      run: pip install -r requirements.txt && pre-commit install
    - name: Run pre-commit
      run: pre-commit run --all-files
