name: Actions
on: [push]

jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.12.2"
    - name: Configure python
      run: pip install -r requirements.txt && pre-commit install
      : # TODO run: pip install --upgrade pip && pip install poetry && poetry install && pip install pre-commit && pre-commit install

    - name: Run pre-commit
      run: pre-commit run --all-files
